"""
issue_materializer.py
=====================
Creates real GitHub Issues from opportunity signals and epic backlog entries.

This is the bridge between "we discovered a problem" and "ForgeOS can work on it"
using the standard pipeline: GitHub Issue → ForgeOS Engine → PR.

No special-case logic. Same pipeline for ForgeOS self-improvement and any other project.
"""
from __future__ import annotations
import os
import json
import time
import requests
from typing import Optional

FORGEOS_REPO = os.getenv("FORGEOS_GITHUB_REPO", "V-Crypto-web/forgeos")
GITHUB_API   = "https://api.github.com"


def _github_headers() -> dict:
    token = os.getenv("GITHUB_TOKEN", "")
    if not token:
        raise RuntimeError("GITHUB_TOKEN not set — cannot create GitHub issues")
    return {
        "Authorization": f"token {token}",
        "Accept":        "application/vnd.github.v3+json",
        "Content-Type":  "application/json",
    }


# ── Issue body builder ────────────────────────────────────────────────────────
def build_issue_body(epic: dict) -> str:
    """Builds a rich GitHub Issue body from an epic/opportunity."""
    epic_id    = epic.get("id", "?")
    desc       = epic.get("description", epic.get("title", "No description"))
    risk_zone  = epic.get("risk_zone", "green")
    priority   = epic.get("priority", "medium")
    source     = epic.get("source", "opportunity_engine")
    metadata   = epic.get("metadata", {})

    # Extract concrete files to modify if available
    files_hint = ""
    if "files" in metadata:
        files_hint = "\n".join(f"- `{f}`" for f in metadata["files"])
    elif "failure_db_path" in metadata:
        files_hint = "- `forgeos/engine/state_machine.py` (patch application logic)"

    examples_section = ""
    examples = metadata.get("examples", [])
    if examples:
        ex = examples[0]
        examples_section = f"""
## Failure Example

```json
{json.dumps(ex, indent=2)[:800]}
```
"""

    return f"""## Problem Summary

{desc}

## Scope

| Field | Value |
|---|---|
| Risk Zone | `{risk_zone}` |
| Priority  | `{priority}` |
| Source    | `{source}` |
| Epic ID   | `{epic_id}` |

## Files to Modify
{files_hint or "_Coder should determine from repo analysis_"}
{examples_section}
## Acceptance Criteria
- [ ] Root cause addressed with a surgical, minimal patch
- [ ] Existing tests pass
- [ ] No regression on OmniBench benchmark

---
*🤖 Auto-generated by ForgeOS Opportunity Engine*
"""


def build_issue_body_from_signal(signal: dict) -> str:
    """Builds GitHub Issue body from an OpportunitySignal."""
    return build_issue_body({
        "id":          signal.get("signature", "opportunity"),
        "description": signal.get("description", signal.get("title", "")),
        "risk_zone":   "green",
        "priority":    "high" if signal.get("score", 0) > 0.7 else "medium",
        "source":      signal.get("source", "opportunity_engine"),
        "metadata":    signal.get("metadata", {}),
    })


# ── GitHub API ────────────────────────────────────────────────────────────────
def create_github_issue(
    title:  str,
    body:   str,
    labels: list[str] = None,
    repo:   str = None,
) -> int:
    """
    Creates a GitHub Issue and returns the real issue number.
    Raises on failure.
    """
    repo   = repo or FORGEOS_REPO
    labels = labels or ["self-improvement"]

    url  = f"{GITHUB_API}/repos/{repo}/issues"
    resp = requests.post(
        url,
        headers=_github_headers(),
        json={"title": title, "body": body, "labels": labels},
        timeout=15,
    )

    if resp.status_code == 201:
        issue_num = resp.json()["number"]
        print(f"[MATERIALIZER] Created issue #{issue_num}: {title[:60]}")
        return issue_num
    elif resp.status_code == 422:
        # Labels may not exist — retry without labels
        resp2 = requests.post(
            url,
            headers=_github_headers(),
            json={"title": title, "body": body},
            timeout=15,
        )
        if resp2.status_code == 201:
            issue_num = resp2.json()["number"]
            print(f"[MATERIALIZER] Created issue #{issue_num} (no labels): {title[:60]}")
            return issue_num
        raise RuntimeError(f"GitHub API error {resp2.status_code}: {resp2.text[:300]}")
    else:
        raise RuntimeError(f"GitHub API error {resp.status_code}: {resp.text[:300]}")


# ── Materialize epics with placeholder issue numbers ──────────────────────────
def materialize_epics_without_issues(
    backlog_path: str,
    repo: str = None,
    dry_run: bool = False,
) -> int:
    """
    Scans improvement_backlog.json for epics with github_issue == 9999 or 0.
    Creates real GitHub Issues for each and updates the backlog.
    Returns count of materialized issues.
    """
    repo = repo or FORGEOS_REPO

    if not os.path.exists(backlog_path):
        print(f"[MATERIALIZER] Backlog not found: {backlog_path}")
        return 0

    with open(backlog_path) as f:
        backlog = json.load(f)

    needs_issue = [
        ep for ep in backlog
        if ep.get("github_issue", 9999) in (0, 9999, None)
        and ep.get("status") not in ("done", "failed")
    ]

    if not needs_issue:
        print("[MATERIALIZER] All active epics already have real GitHub issues ✓")
        return 0

    print(f"[MATERIALIZER] Materializing {len(needs_issue)} epics as GitHub issues…")
    materialized = 0

    for ep in needs_issue:
        try:
            title  = ep.get("title", ep["id"])
            body   = build_issue_body(ep)
            labels = ["self-improvement", ep.get("risk_zone", "green")]

            if dry_run:
                print(f"  [DRY RUN] Would create issue: {title[:70]}")
                ep["github_issue"] = 99999  # Fake number for dry run
                materialized += 1
                continue

            issue_num = create_github_issue(title, body, labels, repo)
            ep["github_issue"] = issue_num
            materialized += 1

            # Short delay to respect GitHub rate limits
            time.sleep(1.5)

        except Exception as e:
            print(f"  [MATERIALIZER ERROR] {ep.get('id')}: {e}")
            continue

    if materialized > 0 and not dry_run:
        with open(backlog_path, "w") as f:
            json.dump(backlog, f, indent=2)
        print(f"[MATERIALIZER] ✓ Materialized {materialized} issues, backlog updated")

    return materialized


# ── Materialize from opportunity signals ──────────────────────────────────────
def materialize_signals_as_issues(
    signals: list[dict],
    backlog_path: str,
    repo: str = None,
    dry_run: bool = False,
) -> list[dict]:
    """
    Takes scored OpportunitySignals, creates GitHub Issues for each,
    and produces new backlog entries (does NOT write to backlog — caller does that).
    Returns list of new epic dicts ready to append to backlog.
    """
    import uuid
    repo     = repo or FORGEOS_REPO
    new_epics: list[dict] = []

    # Load existing backlog to check for duplicates — only block ACTIVE epics.
    # Failed/done epics should NOT permanently blacklist a signal title.
    existing_titles: set[str] = set()
    if os.path.exists(backlog_path):
        try:
            with open(backlog_path) as f:
                bl = json.load(f)
            existing_titles = {
                ep.get("title", "").lower() for ep in bl
                if ep.get("status") not in ("done", "failed")
            }
        except Exception:
            pass

    for sig in signals:
        title = sig.get("title", "ForgeOS Improvement")
        if title.lower() in existing_titles:
            print(f"  [MATERIALIZER] Skipping duplicate: {title[:60]}")
            continue

        try:
            body   = build_issue_body_from_signal(sig)
            labels = ["self-improvement", "opportunity-engine"]

            if dry_run:
                issue_num = 99999
                print(f"  [DRY RUN] Would create: {title[:70]}")
            else:
                try:
                    issue_num = create_github_issue(title, body, labels, repo)
                    time.sleep(1.5)
                except RuntimeError as _gh_err:
                    if "GITHUB_TOKEN" in str(_gh_err) or "token" in str(_gh_err).lower():
                        # No GitHub token — inject locally with placeholder issue number.
                        # materialize_epics_without_issues will create the real issue
                        # when a token becomes available.
                        issue_num = 9999
                        print(f"  [MATERIALIZER] No GitHub token — injecting locally as placeholder: {title[:60]}")
                    else:
                        raise

            epic_id = f"epic-opp-{str(uuid.uuid4())[:8]}"
            new_epic = {
                "id":           epic_id,
                "title":        title,
                "description":  sig.get("description", title),
                "github_issue": issue_num,
                "repo_url":     f"https://github.com/{repo}",
                "status":       "todo",
                "risk_zone":    "green",
                "priority":     "high" if sig.get("score", 0) > 0.7 else "medium",
                "source":       "opportunity_engine",
                "signal_score": sig.get("score", 0),
                "created_by":   "OpportunityEngine",
            }
            new_epics.append(new_epic)
            existing_titles.add(title.lower())

        except Exception as e:
            print(f"  [MATERIALIZER ERROR] signal '{sig.get('signature')}': {e}")
            continue

    return new_epics
